name: 'Setup python and poetry'
description: 'Setup python and poetry'
inputs:
  python_version:
    description: "The version of Python to set up"
    required: true
  poetry_version:
    description: "The version of Poetry to install"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry@${{ inputs.poetry_version }}
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path .virtualenvs
      shell: bash